version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kino-teatr
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - "db:/var/lib/postgresql/data/"

volumes:
  db:
