# Generated by Django 3.2.8 on 2022-05-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('value', models.BigIntegerField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('metrics_name', models.ForeignKey(db_column='id_metrics_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.metricsnamemodel')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.task')),
            ],
            options={
                'db_table': 'metrics',
            },
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(db_column='id_content', primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=200)),
                ('name_content', models.CharField(max_length=100)),
                ('url', models.URLField(null=True)),
                ('success', models.BooleanField(default=False)),
                ('success_date_update', models.DateTimeField(auto_now=True)),
                ('format_content', models.ForeignKey(db_column='id_format_content', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.formatcontentmodel')),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('comment', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.CharField(max_length=255)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.task')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
