# Generated by Django 3.2.8 on 2022-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_commentsmodel_contentmodel_metricsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsmodel',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
